# _config.yml

# Basic Site Settings
locale: "en-US"
theme: "jekyll-theme-default"        # changed from site_theme
title: "刘奕焘的个人主页"
title_separator: "-"
name: &name "刘奕焘"
description: &description "刘奕焘，工程学院地质工程专业2022级本科生。平均学分绩点3.93，位居专业前三，获国家奖学金等7项荣誉。"
url: "https://liuyitaocug.github.io"     # fixed to your GitHub Pages root
baseurl: ""                             
repository: "liuyitaocug/liuyitaocug.github.io"  # fixed to your GitHub repo

# Site Author
author:
  name: "刘奕焘"
  pronouns:
  bio: "刘奕焘，工程学院地质工程专业2022级本科生。平均学分绩点3.93，位居专业前三，获国家奖学金等7项荣誉。学科竞赛方面获全国大学生数学建模竞赛湖北省一等奖、全国大学生数学竞赛三等奖等国家级奖项3项、省级5项。主持参与实验室开放基金项目、大创等科研项目，申请国家发明专利2项，获软著1项，发表北大核心期刊论文1篇。担任砺行宣讲团讲师，累计志愿服务87小时，带队获\"我把地大带回家\"校级实践活动一等奖等奖项。"
  location: "湖北省武汉市"
  employer: "就读于中国地质大学（武汉）"
  uri:
  email: "lyt2003@cug.edu.cn"
  arxiv:
  googlescholar: "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
  impactstory:
  orcid: "http://orcid.org/yourorcidurl"
  semantic:
  pubmed: "https://www.ncbi.nlm.nih.gov/pubmed/?term=john+snow"
  researchgate:
  scopus:
  bitbucket:
  codepen:
  dribbble:
  github: "liuyitaocug"
  kaggle:
  stackoverflow:
  bluesky: "bsky.app"
  facebook:
  flickr:
  foursquare:
  goodreads:
  google_plus:
  keybase:
  instagram:
  lastfm:
  linkedin:
  mastodon:
  medium:
  pinterest:
  soundcloud:
  steam:
  telegram:
  tumblr:
  twitter:
  vine:
  weibo:
  wikipedia:
  xing:
  youtube:
  zhihu:

# Publication Category
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'
  conferences:
    title: 'Conference Papers'

# Site Settings
teaser:
breadcrumbs: false
words_per_minute: 160
future: true
read_more: "disabled"
talkmap_link: false

comments:
  provider:
  disqus:
    shortname:
  discourse:
    server:
  facebook:
    appid:
    num_posts:
    colorscheme:
staticman:
  allowedFields: ['name', 'email', 'url', 'message']
  branch: "gh-pages"
  commitMessage: "New comment."
  filename: comment-{@timestamp}
  format: "yml"
  moderation: true
  path: "_data/comments/{options.slug}"
  requiredFields: ['name', 'email', 'message']
  transforms:
    email: "md5"
  generatedFields:
    date:
      type: "date"
      options:
        format: "iso8601"

atom_feed:
  hide: false
  path:

# Social Sharing
twitter:
  username: &twitter
facebook:
  username:
  app_id:
  publisher:
og_image:
social:
  type:
  name:
  links:

# Analytics
analytics:
  provider: "false"
  google:
    tracking_id:

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"

# Markdown Extensions
markdown_ext:
  - markdown
  - mkdown
  - mkdn
  - mkd
  - md

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Permalinks
permalink: /:categories/:title/
timezone: "Asia/Shanghai"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
  - jekyll-compress-html   # added for HTML compression

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression Config
compress_html:
  clippings: all
  ignore:
    envs: development
