# _config.yml

# Basic Site Settings
title: "刘奕焘的个人主页"
description: "刘奕焘，工程学院地质工程专业2022级本科生。平均学分绩点3.93，位居专业前三，获国家奖学金等7项荣誉。"
baseurl: ""                # the subpath of your site, e.g. "/blog"
url: "https://liuyitaocug.github.io"    # your GitHub Pages URL
theme: "jekyll-theme-default"
repository: "liuyitaocug/liuyitaocug.github.io"

# Author / Profile
author:
  name: "刘奕焘"
  bio: >
    工程学院地质工程专业2022级本科生。平均学分绩点3.93，位居专业前三，
    获国家奖学金等7项荣誉。省级及国家级学科竞赛共获8项奖励。主持/参与多项科研
    与大创项目，申请发明专利2项，获软著1项，发表北大核心期刊论文1篇。
    志愿服务累积87小时，担任砺行宣讲团讲师，并荣获校级实践活动一等奖。
  email: "lyt2003@cug.edu.cn"
  location: "湖北省武汉市"
  employer: "中国地质大学（武汉）"
  github: "liuyitaocug"
  googlescholar: "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
  orcid: "https://orcid.org/yourorcidurl"

# Build Settings
markdown: kramdown
highlighter: rouge
timezone: "Asia/Shanghai"
lsi: false
safe: true

# Markdown Extensions
markdown_ext:
  - markdown
  - mkdn
  - mkd
  - md

# Kramdown Configuration
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# Permalinks & Pagination
permalink: /:categories/:title/
paginate: 5
paginate_path: "/page:num/"

# Collections (if used)
collections:
  posts:
    output: true
  pages:
    output: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Include / Exclude
include:
  - .htaccess
  - _pages
exclude:
  - node_modules
  - vendor
  - Gemfile*
  - Rakefile
  - README*
  - package.json*
  - Gruntfile.js
  - gulpfile.js

# Social Sharing Defaults
twitter:
  username: "liuyitaocug"
facebook:
  publisher: "liuyitaocug"

# RSS Feed
feed:
  path: feed.xml

# Sitemap
sitemap:
  filename: sitemap.xml

# Open Graph / SEO
og_image: "/assets/images/og-default.png"

# Defaults for posts and pages
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author_profile: true
      read_time: true
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      author_profile: true
